"""003_add_empresa_multi_tenant

Revision ID: afff0db3b2a2
Revises: bc7140f965a3
Create Date: 2026-04-18 20:18:34.520626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afff0db3b2a2'
down_revision: Union[str, Sequence[str], None] = 'bc7140f965a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema — multi-tenant with empresa_id."""
    # 1. Crear tabla empresas
    op.create_table('empresas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('rubro', sa.String(length=100), nullable=True),
    sa.Column('moneda', sa.String(length=10), server_default='PYG', nullable=False),
    sa.Column('zona_horaria', sa.String(length=50), server_default='America/Asuncion', nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('idx_empresa_slug', 'empresas', ['slug'], unique=False)

    # 2. Insertar empresa default
    op.execute("INSERT INTO empresas (nombre, slug, rubro) VALUES ('Mi Empresa', 'default', 'General')")

    # 3. Agregar empresa_id como NULLABLE primero (para backfill)
    op.add_column('usuarios', sa.Column('empresa_id', sa.Integer(), nullable=True))
    op.add_column('clientes', sa.Column('empresa_id', sa.Integer(), nullable=True))
    op.add_column('productos', sa.Column('empresa_id', sa.Integer(), nullable=True))
    op.add_column('pedidos', sa.Column('empresa_id', sa.Integer(), nullable=True))
    op.add_column('configuracion', sa.Column('empresa_id', sa.Integer(), nullable=True))

    # 4. Backfill: asignar empresa default (id=1) a todos los registros existentes
    op.execute("UPDATE usuarios SET empresa_id = 1 WHERE empresa_id IS NULL")
    op.execute("UPDATE clientes SET empresa_id = 1 WHERE empresa_id IS NULL")
    op.execute("UPDATE productos SET empresa_id = 1 WHERE empresa_id IS NULL")
    op.execute("UPDATE pedidos SET empresa_id = 1 WHERE empresa_id IS NULL")
    op.execute("UPDATE configuracion SET empresa_id = 1 WHERE empresa_id IS NULL")

    # 5. Alterar empresa_id a NOT NULL
    op.alter_column('usuarios', 'empresa_id', nullable=False)
    op.alter_column('clientes', 'empresa_id', nullable=False)
    op.alter_column('productos', 'empresa_id', nullable=False)
    op.alter_column('pedidos', 'empresa_id', nullable=False)
    op.alter_column('configuracion', 'empresa_id', nullable=False)

    # 6. Crear índices, constraints y FKs
    op.create_index(op.f('ix_usuarios_empresa_id'), 'usuarios', ['empresa_id'], unique=False)
    op.drop_constraint(op.f('usuarios_email_key'), 'usuarios', type_='unique')
    op.create_unique_constraint('uq_usuario_empresa_email', 'usuarios', ['empresa_id', 'email'])
    op.create_foreign_key(None, 'usuarios', 'empresas', ['empresa_id'], ['id'])

    op.create_index(op.f('ix_clientes_empresa_id'), 'clientes', ['empresa_id'], unique=False)
    op.create_unique_constraint('uq_cliente_empresa_celular', 'clientes', ['empresa_id', 'celular'])
    op.create_foreign_key(None, 'clientes', 'empresas', ['empresa_id'], ['id'])

    op.create_index(op.f('ix_productos_empresa_id'), 'productos', ['empresa_id'], unique=False)
    op.drop_constraint(op.f('productos_sku_key'), 'productos', type_='unique')
    op.create_unique_constraint('uq_producto_empresa_sku', 'productos', ['empresa_id', 'sku'])
    op.create_foreign_key(None, 'productos', 'empresas', ['empresa_id'], ['id'])

    op.create_index('idx_pedido_empresa', 'pedidos', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_pedidos_empresa_id'), 'pedidos', ['empresa_id'], unique=False)
    op.create_foreign_key(None, 'pedidos', 'empresas', ['empresa_id'], ['id'])

    op.create_index(op.f('ix_configuracion_empresa_id'), 'configuracion', ['empresa_id'], unique=False)
    op.drop_constraint(op.f('configuracion_clave_key'), 'configuracion', type_='unique')
    op.create_unique_constraint('uq_config_empresa_clave', 'configuracion', ['empresa_id', 'clave'])
    op.create_foreign_key(None, 'configuracion', 'empresas', ['empresa_id'], ['id'])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuarios', type_='foreignkey')
    op.drop_constraint('uq_usuario_empresa_email', 'usuarios', type_='unique')
    op.drop_index(op.f('ix_usuarios_empresa_id'), table_name='usuarios')
    op.create_unique_constraint(op.f('usuarios_email_key'), 'usuarios', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_column('usuarios', 'empresa_id')
    op.drop_constraint(None, 'productos', type_='foreignkey')
    op.drop_constraint('uq_producto_empresa_sku', 'productos', type_='unique')
    op.drop_index(op.f('ix_productos_empresa_id'), table_name='productos')
    op.create_unique_constraint(op.f('productos_sku_key'), 'productos', ['sku'], postgresql_nulls_not_distinct=False)
    op.drop_column('productos', 'empresa_id')
    op.drop_constraint(None, 'pedidos', type_='foreignkey')
    op.drop_index(op.f('ix_pedidos_empresa_id'), table_name='pedidos')
    op.drop_index('idx_pedido_empresa', table_name='pedidos')
    op.drop_column('pedidos', 'empresa_id')
    op.drop_constraint(None, 'configuracion', type_='foreignkey')
    op.drop_constraint('uq_config_empresa_clave', 'configuracion', type_='unique')
    op.drop_index(op.f('ix_configuracion_empresa_id'), table_name='configuracion')
    op.create_unique_constraint(op.f('configuracion_clave_key'), 'configuracion', ['clave'], postgresql_nulls_not_distinct=False)
    op.drop_column('configuracion', 'empresa_id')
    op.drop_constraint(None, 'clientes', type_='foreignkey')
    op.drop_constraint('uq_cliente_empresa_celular', 'clientes', type_='unique')
    op.drop_index(op.f('ix_clientes_empresa_id'), table_name='clientes')
    op.drop_column('clientes', 'empresa_id')
    op.drop_index('idx_empresa_slug', table_name='empresas')
    op.drop_table('empresas')
    # ### end Alembic commands ###
