"""002_add_cliente_producto_pedidoitem_configuracion

Revision ID: bc7140f965a3
Revises: 7c237d1a86e5
Create Date: 2026-04-18 20:01:29.014593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc7140f965a3'
down_revision: Union[str, Sequence[str], None] = '7c237d1a86e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('celular', sa.String(length=20), nullable=False),
    sa.Column('direccion', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('nota', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cliente_celular', 'clientes', ['celular'], unique=False)
    op.create_index(op.f('ix_clientes_celular'), 'clientes', ['celular'], unique=False)
    op.create_table('configuracion',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('clave', sa.String(length=100), nullable=False),
    sa.Column('valor', sa.String(length=500), nullable=False),
    sa.Column('descripcion', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clave')
    )
    op.create_index('idx_config_clave', 'configuracion', ['clave'], unique=False)
    op.create_table('productos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sku', sa.String(length=50), nullable=True),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('precio_base', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('stock', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku')
    )
    op.create_index('idx_producto_nombre', 'productos', ['nombre'], unique=False)
    op.create_table('pedido_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.String(length=300), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_item_pedido', 'pedido_items', ['pedido_id'], unique=False)
    op.create_index(op.f('ix_pedido_items_pedido_id'), 'pedido_items', ['pedido_id'], unique=False)
    op.create_index(op.f('ix_pedido_items_producto_id'), 'pedido_items', ['producto_id'], unique=False)
    op.add_column('pedidos', sa.Column('cliente_id', sa.Integer(), nullable=True))
    op.add_column('pedidos', sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('pedidos', sa.Column('impuestos', sa.Numeric(precision=12, scale=2), nullable=True))
    op.alter_column('pedidos', 'total',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    op.create_index('idx_pedido_cliente', 'pedidos', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_pedidos_cliente_id'), 'pedidos', ['cliente_id'], unique=False)
    op.create_foreign_key(None, 'pedidos', 'clientes', ['cliente_id'], ['id'])
    op.create_foreign_key(None, 'pedidos', 'usuarios', ['usuario_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pedidos', type_='foreignkey')
    op.drop_constraint(None, 'pedidos', type_='foreignkey')
    op.drop_index(op.f('ix_pedidos_cliente_id'), table_name='pedidos')
    op.drop_index('idx_pedido_cliente', table_name='pedidos')
    op.alter_column('pedidos', 'total',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.drop_column('pedidos', 'impuestos')
    op.drop_column('pedidos', 'subtotal')
    op.drop_column('pedidos', 'cliente_id')
    op.drop_index(op.f('ix_pedido_items_producto_id'), table_name='pedido_items')
    op.drop_index(op.f('ix_pedido_items_pedido_id'), table_name='pedido_items')
    op.drop_index('idx_item_pedido', table_name='pedido_items')
    op.drop_table('pedido_items')
    op.drop_index('idx_producto_nombre', table_name='productos')
    op.drop_table('productos')
    op.drop_index('idx_config_clave', table_name='configuracion')
    op.drop_table('configuracion')
    op.drop_index(op.f('ix_clientes_celular'), table_name='clientes')
    op.drop_index('idx_cliente_celular', table_name='clientes')
    op.drop_table('clientes')
    # ### end Alembic commands ###
